import os
import operator
from typing import Annotated, Sequence, TypedDict
from dotenv import load_dotenv

from langchain_core.messages import BaseMessage, HumanMessage, ToolMessage
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.tools import tool
from langgraph.graph import StateGraph, START, END

load_dotenv(dotenv_path='../.env')

# 1. Define State with a Reducer
# When dealing with chat history, we don't want to overwrite the "messages" array.
# We want to APPEND to it. Annotated + operator.add tells LangGraph to do this.
class AgentState(TypedDict):
    messages: Annotated[Sequence[BaseMessage], operator.add]

# 2. Define Tools
@tool
def get_weather(city: str) -> str:
    """Get the current weather in a given city."""
    # Mocked for simplicity
    if city.lower() == "tokyo":
        return "It is currently 75F and sunny in Tokyo."
    elif city.lower() == "london":
        return "It is currently 50F and raining in London."
    return f"I don't have weather data for {city}."

tools = [get_weather]
tools_by_name = {tool.name: tool for tool in tools}

# 3. Define the LLM Node
def call_model(state: AgentState):
    print("--- 🤖 Model is Thinking ---")
    llm = ChatGoogleGenerativeAI(model="gemini-1.5-flash")
    # Bind the tools to the LLM so it knows it can call them
    llm_with_tools = llm.bind_tools(tools)
    
    response = llm_with_tools.invoke(state["messages"])
    
    # Return the new message to be appended to state
    return {"messages": [response]}

# 4. Define the Tool Execution Node
def execute_tools(state: AgentState):
    print("--- 🔧 Model Decided to Use Tools ---")
    last_message = state["messages"][-1]
    
    # A model might request multiple tool calls at once
    responses = []
    for tool_call in last_message.tool_calls:
        tool_name = tool_call["name"]
        tool_args = tool_call["args"]
        print(f"    [Executing {tool_name} with {tool_args}]")
        
        # Get the actual python function and call it
        action = tools_by_name[tool_name]
        result = action.invoke(tool_args)
        
        # Wrap result in a ToolMessage to feed back to the LLM
        responses.append(ToolMessage(content=str(result), tool_call_id=tool_call["id"]))
        
    return {"messages": responses}

# 5. Define Conditional Routing Logic
def should_continue(state: AgentState) -> str:
    # Look at the last message generated by the LLM
    last_message = state["messages"][-1]
    
    # If there are tool calls, we must route to the tool executor
    if last_message.tool_calls:
        return "tools"
    # Otherwise, it's just a normal conversational response, we are finished!
    return "end"

def main():
    print("🚀 Starting Manual LangGraph Agent")

    # 6. Build Graph
    builder = StateGraph(AgentState)

    builder.add_node("agent", call_model)
    builder.add_node("tools", execute_tools)

    builder.add_edge(START, "agent")
    
    # Conditional Edge: From 'agent', run 'should_continue'. 
    # If it returns 'tools', go to 'tools'. If 'end', go to END.
    builder.add_conditional_edges(
        "agent",
        should_continue,
        {"tools": "tools", "end": END}
    )
    
    # After tools execute, ALWAYS go back to the agent so it can read 
    # the tool result and decide the next step (or final answer).
    builder.add_edge("tools", "agent")

    graph = builder.compile()

    # 7. Run it!
    query = "What is the weather like in Tokyo right now?"
    print(f"\n--- User: {query} ---")
    
    initial_state = {"messages": [HumanMessage(content=query)]}
    final_state = graph.invoke(initial_state)

    print("\n--- ✅ Final Answer ---")
    print(final_state["messages"][-1].content)

    print("\n--- 🧠 Why we did this ---")
    print("In Project 4, we used 'create_react_agent' to hide all this magic.")
    print("By building the Agent graph manually, you now understand the mechanics")
    print("of Tool Calling. You also have the power to customize the workflow:")
    print("e.g. adding a 'SanntiyCheck' node after tools, or forcing specific tools")
    print("to run before the agent even sees the prompt.")

if __name__ == "__main__":
    main()
